tables:
  logs: bm_server_logs
  reportLogs: bm_report_logs
  playerPins: bm_player_pins
# Number of lines to log with each report
lines: 30
# Allows using regex to filter logs
ignorePatterns:
# Basic contain checks
ignoreContains:
- 'issued server command: /report'
- 'has been reported by'
- '[BanManager]'
- '[PlugMan]'
- 'Metrics'
- 'For help, type "help"'
